services:
    postgres:
        image: postgres:16-alpine
        container_name: postgres-db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=skillstasks
        ports:
            - "5432:5432"
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 5s
            retries: 5

    app:
        build:
            context: ./back/app
            dockerfile: Dockerfile
        container_name: backend-service
        networks:
            - app-network
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/skillstasks
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
            - SPRING_LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.yaml
            - SPRING_LIQUIBASE_DRIVER_CLASS_NAME=org.postgresql.Driver
            - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/skillstasks
            - SPRING_LIQUIBASE_USER=postgres
            - SPRING_LIQUIBASE_PASSWORD=postgres
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy

    front:
        build:
            context: ./front/hackathon_groupe_3
            dockerfile: Dockerfile.dev
        container_name: frontend-service
        networks:
            - app-network
        ports:
            - "3000:3000"
        volumes:
            - ./front/hackathon_groupe_3:/app
            - /app/node_modules

networks:
    app-network:
        driver: bridge
