# Étape 1 : Utiliser une image Node officielle
FROM node:18-alpine

# Étape 2 : Définir le répertoire de travail
WORKDIR /app

# Étape 3 : Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 6 : Exposer le port utilisé par Nuxt (par défaut 3000)
EXPOSE 3000

# Étape 7 : Lancer Nuxt en mode développement
CMD ["npm", "run", "dev"]