apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-service-deployment
  namespace: auth-namespace
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ldap-service
  template:
    metadata:
      labels:
        app: ldap-service
    spec:
      containers:
        - name: openldap
          image: hackathon2025/openldap_with_data:latest
          ports:
            - containerPort: 1389
          livenessProbe:
            exec:
              command: [ "ldapsearch", "-H", "ldap://localhost:1389", "-D", "cn=admin,dc=istic,dc=fr", "-w", "adminpassword", "-b", "dc=istic,dc=fr" ]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
