apiVersion: v1
kind: Service
metadata:
  name: ldap-service-gateway
  namespace: auth-namespace
spec:
  selector:
    app: ldap-service
  ports:
    - protocol: TCP
      port: 1389       # Port utilisé à l'intérieur du cluster
      targetPort: 1389 # Port exposé par le conteneur OpenLDAP
      nodePort: 32370  # Port accessible depuis l'extérieur
  type: NodePort       # Type pour exposer en dehors du cluster