apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-namespace
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  
