apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-namespace
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  

apiVersion: v1
kind: Service
metadata:
  name: ldap-service
  namespace: auth-namespace
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 1389        # Port interne du cluster
      targetPort: 1389  # Port du container OpenLDAP
      nodePort: 32389   # Port accessible depuis l'extérieur
  type: NodePort