apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: auth-namespace
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth
        image: hackathon2025/skillstasks_repo-auth:latest
        ports:
        - containerPort: 8080
