apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-namespace
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Port exposé par le conteneur OpenLDAP
      nodePort: 32385  # Port accessible depuis l'extérieur
  type: NodePort       # Type pour exposer en dehors du cluster
