apiVersion: v1
kind: Service
metadata:
  name: auth-service-gateway
  namespace: auth-namespace
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081  
  type: ClusterIP